name: Snapshot Build
on:
  push:
    branches:
      master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: Build (Windows)
    if: github.repository == 'KM198912/CC65'
    runs-on: windows-latest

    steps:
      - shell: bash
        run: git config --global core.autocrlf input

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app (debug)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Debug

      - name: Build app (release)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release

  build_linux:
    name: Build, Test, and Snapshot (Linux)
    if: github.repository == 'KM198912/CC65'
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install linuxdoc-tools-info gcc-mingw-w64-x86-64 gcc-mingw-w64-i686

      - shell: bash
        run: git config --global core.autocrlf input
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Do some simple style checks
        shell: bash
        run: make -j2 checkstyle
      - name: Build the tools.
        shell: bash
        run: |
            make -j2 bin USER_CFLAGS=-Werror
            make -j2 util
      - name: Build the platform libraries.
        shell: bash
        run: make -j2 lib QUIET=1
      - name: Remove programs in util directory
        shell: bash
        run: make -C util clean

      # TODO: Publish snapshot zip at https://github.com/cc65/cc65.github.io
